name: Commando Training
on: [push, pull_request]
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install fmt manually
      run: git clone https://github.com/fmtlib/fmt
        && cd fmt
        && cmake . -DFMT_TEST=FALSE
        && sudo make -j install
    - name: Install spdlog manually
      run: git clone https://github.com/gabime/spdlog
        && cd spdlog
        && cmake .
        && sudo make -j install
    - name: Compilation and execution
      uses: spoutn1k/mcmap-benchmark@cmake
    - name: Upload time data
      uses: actions/upload-artifact@v1
      with:
        name: results.log
        path: time.log
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: images.tgz
        path: images.tgz
